include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - prefer_single_quotes
    - require_trailing_commas
    - use_super_parameters
    - unawaited_futures
    - avoid_print
    - directives_ordering
