import 'legal_document.dart';
import 'legal_entity.dart';

/// Wishtick's Terms & Conditions, transcribed from the executed document.
///
/// The clause text is reproduced as written — this file is a transcription,
/// not a rewrite, and edits to wording belong with counsel, not here. The only
/// departures are the blanks the signed copy left open, each resolved through
/// [LegalEntity] with the reasoning recorded there.
///
/// The [LegalCallout]s are additions rather than transcription: plain-language
/// summaries sitting beside the clauses they summarise. They are marked as
/// summaries in the UI and change nothing about what the clause says.
abstract final class TermsDocument {
  static const document = LegalDocument(
    title: 'Terms & Conditions',
    kicker: 'The agreement between you and Wishtick',
    summary:
        'These Terms govern your use of Wishtick — wishlists, registries, '
        'events, gifting groups and everything you discover through them.',
    entity: LegalEntity.name,
    effectiveDate: LegalEntity.effectiveDate,
    intro: [
      LegalCallout(
        'Wishtick helps you find, share and coordinate gifts. It does not '
        'sell them — every purchase happens on a partner retailer’s own site, '
        'under their terms.',
      ),
      LegalCallout(
        'You keep ownership of everything you post. Ticking the consent box '
        'is what makes this agreement binding.',
        tone: LegalTone.good,
      ),
      LegalParagraph(
        'CIN: ${LegalEntity.cin}. GSTIN: ${LegalEntity.gstin}. '
        'Website: ${LegalEntity.website}.',
      ),
    ],
    sections: [
      LegalSection(1, 'Definitions', [
        LegalClause(
          '1.1',
          '“Account” means the registered user profile created by a User on '
              'the Platform.',
        ),
        LegalClause(
          '1.2',
          '“Affiliate Partner” means a third-party retailer, brand, or '
              'e-commerce platform with which Wishtick has a referral, '
              'affiliate, or similar commercial arrangement enabling Users to '
              'discover or purchase Products.',
        ),
        LegalClause(
          '1.3',
          '“AI Recommendation” means any wishlist, product, gifting, or '
              'occasion suggestion generated by Wishtick’s algorithmic or '
              'machine-learning systems.',
        ),
        LegalClause(
          '1.4',
          '“Content” means text, images, wishlists, registries, event '
              'details, comments, or any other material uploaded, posted, or '
              'generated by a User on the Platform.',
        ),
        LegalClause(
          '1.5',
          '“Event” means a birthday, wedding, anniversary, baby shower, '
              'festive occasion, or other occasion for which a User creates a '
              'Registry or wishlist.',
        ),
        LegalClause(
          '1.6',
          '“Gifting Group” means a private group of Users created for the '
              'purpose of coordinating group gifts or participating in an '
              'Event together.',
        ),
        LegalClause(
          '1.7',
          '“Platform” means the Wishtick website, mobile application(s), and '
              'any related services operated by ${LegalEntity.name}.',
        ),
        LegalClause(
          '1.8',
          '“Products” means goods or services listed by third-party Affiliate '
              'Partners or retailers and discoverable through the Platform.',
        ),
        LegalClause(
          '1.9',
          '“Registry” means a curated public or private list of desired gifts '
              'created by a User in connection with an Event.',
        ),
        LegalClause(
          '1.10',
          '“User,” “you,” “your” means any individual who accesses, registers '
              'on, or uses the Platform.',
        ),
        LegalClause(
          '1.11',
          '“User Generated Content” or “UGC” has the meaning given in '
              'Clause 19.',
        ),
        LegalClause(
          '1.12',
          '“Wishlist” means a list of desired products or items created by a '
              'User for personal or shared reference.',
        ),
        LegalClause(
          '1.13',
          'Terms not defined here carry the meaning assigned under the '
              'Information Technology Act, 2000, the Digital Personal Data '
              'Protection Act, 2023, and the Consumer Protection Act, 2019, '
              'as applicable.',
        ),
      ]),

      LegalSection(2, 'Acceptance of Terms', [
        LegalClause(
          '2.1',
          'These Terms & Conditions (“Terms”), together with the Privacy '
              'Policy and any other policies referenced herein, constitute a '
              'legally binding agreement between you and Wishtick governing '
              'your access to and use of the Platform.',
        ),
        LegalClause(
          '2.2',
          'By creating an Account, clicking “I Agree,” or otherwise accessing '
              'or using the Platform, you confirm that you have read, '
              'understood, and agree to be bound by these Terms, in '
              'accordance with Section 10 of the Indian Contract Act, 1872.',
        ),
        LegalClause(
          '2.3',
          'If you do not agree to these Terms in their entirety, you must not '
              'access or use the Platform.',
        ),
        LegalClause(
          '2.4',
          'These Terms apply to all Users, irrespective of the mode of access '
              '(web, mobile application, API, or otherwise).',
        ),
      ]),

      LegalSection(3, 'Eligibility', [
        LegalClause(
          '3.1',
          'You must be at least 18 years of age and competent to contract '
              'under the Indian Contract Act, 1872, to independently create '
              'an Account.',
        ),
        LegalClause(
          '3.2',
          'Users between 13 and 18 years of age may use the Platform only '
              'under the supervision of, and with an Account registered by, a '
              'parent or legal guardian who accepts these Terms on the '
              'minor’s behalf. Wishtick does not knowingly permit independent '
              'account creation by anyone below 18. See Privacy Policy '
              'Clause 33 for provisions specific to children’s data under the '
              'DPDP Act, 2023.',
        ),
        LegalClause(
          '3.3',
          'By registering, you represent and warrant that all information '
              'provided is true, accurate, and complete, and that you have '
              'the legal capacity to enter into this agreement.',
        ),
        LegalClause(
          '3.4',
          'Wishtick reserves the right to refuse registration or terminate '
              'access where eligibility criteria are not met or are '
              'reasonably suspected not to be met.',
        ),
      ]),

      LegalSection(4, 'User Registration', [
        LegalClause(
          '4.1',
          'Access to certain features requires registration using a valid '
              'mobile number, email address, or supported third-party sign-in '
              '(e.g., Google/Apple sign-in).',
        ),
        LegalClause(
          '4.2',
          'You agree to provide accurate registration information and to '
              'promptly update it if it changes.',
        ),
        LegalClause(
          '4.3',
          'Each individual may maintain only one active Account unless '
              'expressly permitted otherwise by Wishtick.',
        ),
        LegalClause(
          '4.4',
          'Wishtick may, at its discretion, verify identity information '
              'through OTP or other means before activating certain features '
              '(see Clause 6).',
        ),
        LegalClause(
          '4.5',
          'Wishtick reserves the right to reject any registration or Account '
              'without being obliged to disclose reasons, subject to '
              'applicable law.',
        ),
      ]),

      LegalSection(5, 'Account Security', [
        LegalClause(
          '5.1',
          'You are solely responsible for maintaining the confidentiality of '
              'your Account credentials, OTPs, and login sessions.',
        ),
        LegalClause(
          '5.2',
          'You must notify Wishtick immediately at '
              '${LegalEntity.supportEmail} upon becoming aware of any '
              'unauthorized access to or use of your Account.',
        ),
        LegalClause(
          '5.3',
          'Wishtick is not liable for any loss or damage arising from your '
              'failure to comply with this Clause 5, including where '
              'credentials are shared, guessed, or obtained through your own '
              'negligence.',
        ),
        LegalClause(
          '5.4',
          'Wishtick may suspend Account access where it reasonably suspects '
              'unauthorized use, security compromise, or fraudulent activity, '
              'and will notify you through registered contact details where '
              'practicable.',
        ),
      ]),

      LegalSection(6, 'OTP Verification', [
        LegalCallout(
          'Wishtick will never ask for your OTP over a call, a chat, or an '
          'email. Anyone who does is not us.',
          tone: LegalTone.caution,
        ),
        LegalClause(
          '6.1',
          'Wishtick uses One-Time Password (“OTP”) verification via SMS '
              'and/or email to authenticate registration, login, password '
              'reset, and certain sensitive actions (e.g., changing linked '
              'mobile number).',
        ),
        LegalClause(
          '6.2',
          'You must not share your OTP with any person. Wishtick will never '
              'ask for your OTP over phone calls, chat, or email.',
        ),
        LegalClause(
          '6.3',
          'Repeated failed OTP attempts may result in temporary lock-out of '
              'the relevant action as a fraud-prevention measure.',
        ),
        LegalClause(
          '6.4',
          'OTPs are time-bound and single-use; expired OTPs must be '
              'regenerated.',
        ),
      ]),

      LegalSection(7, 'User Responsibilities', [
        LegalClause(
          '7.1',
          'You agree to use the Platform only for lawful purposes connected '
              'with personal wishlists, gift registries, event planning, and '
              'gifting-related discovery and communication.',
        ),
        LegalClause(
          '7.2',
          'You are solely responsible for the accuracy of Wishlist, Registry, '
              'Event, and Gifting Group information you create or share.',
        ),
        LegalClause(
          '7.3',
          'You are responsible for obtaining the consent of any third party '
              '(e.g., a friend or family member) before adding their contact '
              'details, sharing their information, or inviting them to a '
              'Gifting Group.',
        ),
        LegalClause(
          '7.4',
          'You must not misrepresent your identity or impersonate another '
              'person or entity.',
        ),
        LegalClause(
          '7.5',
          'You are responsible for all activity that occurs under your '
              'Account, whether or not authorized by you, except to the '
              'extent caused by Wishtick’s breach of these Terms.',
        ),
      ]),

      LegalSection(8, 'Acceptable Use Policy', [
        LegalClause(
          '8.1',
          'You agree to use the Platform in a manner consistent with its '
              'intended purpose — personal and social gifting, wishing, and '
              'celebration — and not to:',
          items: [
            'use the Platform for commercial solicitation not authorized by '
                'Wishtick;',
            'scrape, harvest, or extract data from the Platform using '
                'automated means without prior written consent;',
            'reverse-engineer, decompile, or attempt to derive source code of '
                'the Platform or its AI systems;',
            'circumvent or attempt to circumvent security, rate-limiting, or '
                'access-control measures;',
            'use the Platform to transmit unsolicited commercial '
                'communications (“spam”) to other Users.',
          ],
        ),
        LegalClause(
          '8.2',
          'Wishtick may monitor use of the Platform to enforce this '
              'Acceptable Use Policy, subject to the Privacy Policy.',
        ),
      ]),

      LegalSection(9, 'Prohibited Activities', [
        LegalClause(
          '9.1',
          'Without limiting Clause 8, you must not use the Platform to:',
          items: [
            'upload, post, or transmit unlawful, defamatory, obscene, '
                'pornographic, paedophilic, invasive of another’s privacy, '
                'hateful, or racially or ethnically objectionable content, or '
                'content that violates any applicable law, consistent with '
                'Rule 3(1)(b) of the Information Technology (Intermediary '
                'Guidelines and Digital Media Ethics Code) Rules, 2021;',
            'infringe any patent, trademark, copyright, or other proprietary '
                'right of any party;',
            'threaten the unity, integrity, defence, security, or sovereignty '
                'of India, or public order;',
            'deceive or mislead recipients about the origin of a message or '
                'knowingly and intentionally communicate misinformation;',
            'impersonate another person, create fake Registries or Events, or '
                'engage in gift-fraud schemes;',
            'upload viruses, malware, or any code designed to disrupt or '
                'damage the Platform;',
            'engage in harassment, stalking, or threatening behaviour toward '
                'another User through Gifting Groups, comments, or shared '
                'Content;',
            'use the AI Recommendation or SOS/urgent-gifting features (where '
                'launched) for purposes unrelated to genuine gifting needs, '
                'including to defraud other Users or Affiliate Partners.',
          ],
        ),
        LegalClause(
          '9.2',
          'Violation of this Clause may result in content removal, Account '
              'suspension, termination, and/or reporting to law enforcement '
              'authorities, without prejudice to Wishtick’s other rights and '
              'remedies.',
        ),
      ]),

      LegalSection(10, 'Public and Private Wishlists', [
        LegalClause(
          '10.1',
          'Users may create Wishlists and designate them as “public” '
              '(discoverable by other Users or, where enabled, the general '
              'public) or “private” (visible only to the User and those '
              'expressly invited).',
        ),
        LegalClause(
          '10.2',
          'You are responsible for selecting the appropriate visibility '
              'setting for each Wishlist. Wishtick is not responsible for '
              'consequences arising from a User’s choice to make a Wishlist '
              'public.',
        ),
        LegalClause(
          '10.3',
          'Wishtick does not guarantee that any product listed on a Wishlist '
              'will remain available, correctly priced, or in stock on the '
              'Affiliate Partner’s website, as these are outside Wishtick’s '
              'control (see Clauses 14–16).',
        ),
        LegalClause(
          '10.4',
          'Wishtick may, for product-discovery and AI-personalization '
              'purposes, analyze aggregated and/or de-identified Wishlist '
              'data as described in the Privacy Policy.',
        ),
      ]),

      LegalSection(11, 'Gift Registries', [
        LegalClause(
          '11.1',
          'Wishtick gift registries function similarly to Wishlists but are '
              'associated with a specific Event (e.g., wedding, baby shower) '
              'and may support additional features such as guest access '
              'links, contribution tracking (where introduced), and '
              'Event-specific reminders.',
        ),
        LegalClause(
          '11.2',
          'The User creating a Wishtick Registry is solely responsible for '
              'the accuracy of Event details and for managing who is granted '
              'access to a private Registry.',
        ),
        LegalClause(
          '11.3',
          'Wishtick does not process, hold, or guarantee delivery of gifts, '
              'cash contributions, or monetary pooling in connection with a '
              'Registry unless and until a payment or wallet feature is '
              'formally launched and separately disclosed with updated Terms.',
        ),
        LegalClause(
          '11.4',
          'Registry data may be retained beyond the Event date for '
              'historical/gifting-history purposes as described in the '
              'Privacy Policy, unless the User requests deletion.',
        ),
      ]),

      LegalSection(12, 'Group Gifting Rules', [
        LegalCallout(
          'Money in a group gift moves between you and the people you are '
          'gifting with. Wishtick does not collect, hold or disburse it.',
          tone: LegalTone.caution,
        ),
        LegalClause(
          '12.1',
          '“Group Gifting” allows multiple Users to coordinate contribution '
              'toward, or joint selection of, a gift for a Registry or Event, '
              'currently through visibility and coordination features and '
              'communication features within a Gifting Group.',
        ),
        LegalClause(
          '12.2',
          'Wishtick is a facilitator of coordination and discovery only. '
              'Unless and until a payment/wallet/escrow feature is live and '
              'governed by updated, RBI-compliant Terms, Wishtick does not '
              'collect, pool, hold, or disburse funds among Users '
              'participating in Group Gifting, and any monetary arrangement '
              'between Users is a private arrangement between those Users for '
              'which Wishtick bears no responsibility.',
        ),
        LegalClause(
          '12.3',
          'Members of a Gifting Group are responsible for their own conduct '
              'and communications within the group. Wishtick reserves the '
              'right to remove content or members violating Clause 9.',
        ),
        LegalClause(
          '12.4',
          'Where in-group communication features are introduced, Clauses 8, '
              '9, and 19 (User Generated Content) apply equally to messages '
              'sent within a Gifting Group.',
        ),
      ]),

      LegalSection(13, 'AI Recommendations Disclaimer', [
        LegalClause(
          '13.1',
          'Wishtick uses artificial intelligence and machine-learning systems '
              'to generate personalized gift, product, and occasion '
              'recommendations based on Wishlist activity, stated '
              'preferences, Event data, and other information described in '
              'the Privacy Policy.',
        ),
        LegalClause(
          '13.2',
          'AI Recommendations are provided for convenience only and do not '
              'constitute advice, endorsement, or a guarantee of suitability, '
              'availability, price accuracy, or quality of any recommended '
              'Product.',
        ),
        LegalClause(
          '13.3',
          'Wishtick does not warrant that AI Recommendations will be '
              'error-free, unbiased, or reflective of the best or cheapest '
              'available option, and disclaims liability for purchase '
              'decisions made in reliance on AI Recommendations.',
        ),
        LegalClause(
          '13.4',
          'Users may, where such controls are made available, opt out of '
              'personalized AI Recommendations through Account settings, '
              'consistent with Privacy Policy Clause 9 and Clause 19.',
        ),
      ]),

      LegalSection(14, 'Affiliate Marketing Disclaimer', [
        LegalCallout(
          'When you buy through a Wishtick link we may earn a commission. It '
          'does not change the price you pay.',
          tone: LegalTone.good,
        ),
        LegalClause(
          '14.1',
          'Wishtick participates in affiliate marketing arrangements with '
              'third-party retailers and platforms. When you click through to '
              'and/or purchase a Product via an Affiliate Partner link, '
              'Wishtick may earn a commission or referral fee from the '
              'Affiliate Partner. This does not increase the price you pay.',
        ),
        LegalClause(
          '14.2',
          'The display or recommendation of a Product does not constitute '
              'Wishtick’s endorsement of the Affiliate Partner, the Product, '
              'or its quality, and rankings may be influenced by commercial '
              'arrangements, which Wishtick will seek to disclose where '
              'materially relevant, consistent with Consumer Protection Act, '
              '2019 requirements around endorsements and disclosures.',
        ),
        LegalClause(
          '14.3',
          'Wishtick is not a party to, and bears no responsibility for, the '
              'contract of sale formed between you and the Affiliate Partner.',
        ),
      ]),

      LegalSection(15, 'Third-Party Products', [
        LegalClause(
          '15.1',
          'Wishtick does not manufacture, sell, warehouse, ship, or fulfil '
              'any Products. All Products are offered, sold, and fulfilled '
              'exclusively by third-party Affiliate Partners and retailers.',
        ),
        LegalClause(
          '15.2',
          'Product descriptions, images, pricing, availability, and delivery '
              'timelines are provided by or sourced from Affiliate Partners '
              'and are subject to change without notice; Wishtick does not '
              'independently verify their accuracy and disclaims liability '
              'for discrepancies.',
        ),
        LegalClause(
          '15.3',
          'Any dispute regarding a Product — including quality, authenticity, '
              'delivery, damage, or non-delivery — is solely between you and '
              'the relevant Affiliate Partner/retailer, and must be resolved '
              'directly with them under their applicable terms, warranties, '
              'and return/refund policies.',
        ),
        LegalClause(
          '15.4',
          'Wishtick will make reasonable efforts to direct grievances to the '
              'concerned Affiliate Partner where feasible but assumes no '
              'obligation or liability to resolve such disputes.',
        ),
      ]),

      LegalSection(16, 'Third-Party Links', [
        LegalClause(
          '16.1',
          'The Platform contains links to third-party websites and '
              'applications operated by Affiliate Partners and other parties '
              'not controlled by Wishtick.',
        ),
        LegalClause(
          '16.2',
          'Wishtick does not review, control, or endorse the content, privacy '
              'practices, or terms of use of such third-party sites, and is '
              'not responsible for them.',
        ),
        LegalClause(
          '16.3',
          'Accessing third-party links is at your own risk, and you should '
              'review the applicable third party’s terms and privacy policy '
              'before transacting.',
        ),
      ]),

      LegalSection(17, 'Payment Terms (Current and Future)', [
        LegalClause(
          '17.1',
          'Current state: Wishtick does not currently process payments, hold '
              'funds, or operate a wallet. Purchases of Products occur '
              'entirely on the Affiliate Partner’s platform, under that '
              'Affiliate Partner’s payment terms.',
        ),
        LegalClause(
          '17.2',
          'Future state: Should Wishtick introduce payment gateway '
              'integration, wallet functionality, gift cards, premium '
              'subscriptions, or marketplace transactions, such features will '
              'be governed by supplementary payment terms, updated in '
              'compliance with applicable RBI guidelines (including, as '
              'relevant, the Payment Aggregator/Payment Gateway framework), '
              'the Consumer Protection (E-Commerce) Rules, 2020, and this '
              'Clause 17 will be amended accordingly with prior notice under '
              'Clause 40.',
        ),
        LegalClause(
          '17.3',
          'Any future premium subscription fees, where introduced, will be '
              'clearly disclosed with pricing, billing frequency, '
              'auto-renewal terms, and cancellation mechanics prior to '
              'purchase, in compliance with applicable consumer protection '
              'law.',
        ),
      ]),

      LegalSection(18, 'Refunds and Cancellations', [
        LegalClause(
          '18.1',
          'Third-party Product purchases: Since Products are sold by '
              'Affiliate Partners, refunds and cancellations for such '
              'purchases are governed entirely by the Affiliate Partner’s own '
              'refund/cancellation policy. Wishtick is not responsible for '
              'processing or guaranteeing such refunds.',
        ),
        LegalClause(
          '18.2',
          'Wishtick-billed services (future): For any service billed directly '
              'by Wishtick in the future (e.g., premium subscription), a '
              'separate refund and cancellation policy will be published at '
              'the time of launch, consistent with the Consumer Protection '
              'Act, 2019 and applicable RBI/payment-network rules.',
        ),
        LegalClause(
          '18.3',
          'Nothing in this Clause affects your statutory rights as a consumer '
              'under the Consumer Protection Act, 2019 against the actual '
              'seller of a Product.',
        ),
      ]),

      LegalSection(19, 'User Generated Content', [
        LegalClause(
          '19.1',
          '“User Generated Content” or “UGC” includes Wishlists, Registries, '
              'Event details, comments, reviews, images, and any other '
              'Content you upload or create on the Platform.',
        ),
        LegalClause(
          '19.2',
          'You represent that you own or have the necessary rights to post '
              'your UGC, and that it does not violate any third party’s '
              'rights or Clause 9 (Prohibited Activities).',
        ),
        LegalClause(
          '19.3',
          'Wishtick acts as an intermediary within the meaning of Section '
              '2(1)(w) of the Information Technology Act, 2000, with respect '
              'to UGC and observes due diligence under Section 79 and the '
              'Intermediary Guidelines Rules, 2021, including maintaining a '
              'grievance mechanism (Clause 38) and acting on actionable '
              'complaints and lawful orders.',
        ),
        LegalClause(
          '19.4',
          'Wishtick reserves the right, but is not obligated, to review, '
              'moderate, or remove UGC that violates these Terms, applicable '
              'law, or upon receipt of a valid complaint or government/court '
              'order.',
        ),
      ]),

      LegalSection(20, 'Ownership of Content', [
        LegalCallout(
          'Your wishlists, photos and words stay yours. The licence below is '
          'what lets us store them and show them to the people you share '
          'them with.',
          tone: LegalTone.good,
        ),
        LegalClause(
          '20.1',
          'As between you and Wishtick, you retain ownership of the UGC you '
              'create, subject to the licence granted in Clause 20.2.',
        ),
        LegalClause(
          '20.2',
          'By posting UGC on the Platform, you grant Wishtick a worldwide, '
              'non-exclusive, royalty-free, sub-licensable licence to host, '
              'store, reproduce, display, adapt (for formatting/technical '
              'purposes), and distribute such UGC solely for the purposes of '
              'operating, promoting, and improving the Platform (including AI '
              'Recommendation training on an aggregated/de-identified basis, '
              'unless you opt out where such controls are available), for so '
              'long as the UGC remains on the Platform and for a reasonable '
              'period thereafter for backup and legal-compliance purposes.',
        ),
        LegalClause(
          '20.3',
          'This licence does not transfer ownership and terminates (save for '
              'residual backup/compliance copies and any UGC shared with or '
              'already visible to other Users) upon deletion of the relevant '
              'UGC or your Account, subject to Clause 28 (Data Retention).',
        ),
      ]),

      LegalSection(21, 'Intellectual Property Rights', [
        LegalClause(
          '21.1',
          'All intellectual property in the Platform — including its '
              'software, source code, AI models, design, “look and feel,” '
              'databases, and compilations (excluding UGC and third-party '
              'content) — is owned by or licensed to Wishtick and is '
              'protected under the Copyright Act, 1957, the Trade Marks Act, '
              '1999, and other applicable Indian and international '
              'intellectual property laws.',
        ),
        LegalClause(
          '21.2',
          'No right, title, or interest in the Platform’s intellectual '
              'property is transferred to you by virtue of using the '
              'Platform, other than the limited, revocable, non-exclusive '
              'licence to access and use the Platform for its intended '
              'personal, non-commercial purpose.',
        ),
        LegalClause(
          '21.3',
          'You must not copy, modify, distribute, sell, or lease any part of '
              'the Platform’s software or derive its source code, except as '
              'permitted by applicable law.',
        ),
      ]),

      LegalSection(22, 'Trademark Protection', [
        LegalClause(
          '22.1',
          '“Wishtick,” the Wishtick logo, and associated brand marks are '
              'trademarks of ${LegalEntity.name} (registered or pending '
              'registration, as applicable).',
        ),
        LegalClause(
          '22.2',
          'You must not use Wishtick’s trademarks, brand assets, or trade '
              'dress without prior written consent, including in a manner '
              'that suggests endorsement, affiliation, or sponsorship that '
              'does not exist.',
        ),
        LegalClause(
          '22.3',
          'Unauthorized use of Wishtick’s trademarks may result in legal '
              'action under the Trade Marks Act, 1999.',
        ),
      ]),

      LegalSection(23, 'Copyright Policy', [
        LegalClause(
          '23.1',
          'Wishtick respects the intellectual property rights of others and '
              'expects Users to do the same.',
        ),
        LegalClause(
          '23.2',
          'Users must not upload UGC that infringes any third party’s '
              'copyright, including copyrighted images, text, or media used '
              'without authorization.',
        ),
        LegalClause(
          '23.3',
          'Wishtick will act on valid takedown requests in accordance with '
              'Clause 24 and Section 79 of the Information Technology Act, '
              '2000.',
        ),
      ]),

      LegalSection(24, 'Copyright Infringement Procedure', [
        LegalClause(
          '24.1',
          'If you believe that Content on the Platform infringes your '
              'copyright, you may submit a written notice to the Grievance '
              'Officer (Clause 38) including:',
          items: [
            'identification of the copyrighted work claimed to be infringed;',
            'identification and location (URL/screen) of the allegedly '
                'infringing material;',
            'your contact details;',
            'a statement of good-faith belief that the use is unauthorized; '
                'and',
            'a statement, under penalty of perjury, that the information is '
                'accurate and that you are authorized to act on behalf of the '
                'rights owner.',
          ],
        ),
        LegalClause(
          '24.2',
          'On receipt of a valid notice, Wishtick will act expeditiously, '
              'consistent with its obligations as an intermediary under the '
              'Information Technology Act, 2000 and the Intermediary '
              'Guidelines Rules, 2021, which generally requires removal or '
              'disabling of access within the statutory timeframe (currently '
              '36 hours for specified categories of complaints).',
        ),
        LegalClause(
          '24.3',
          'Wishtick may, where appropriate, notify the User who posted the '
              'material and provide an opportunity to respond, without '
              'prejudice to its obligation to act on valid legal notices.',
        ),
      ]),

      LegalSection(25, 'Community Guidelines', [
        LegalClause(
          '25.1',
          'Users are expected to engage respectfully within Gifting Groups, '
              'comments, and shared Registries/Wishlists.',
        ),
        LegalClause(
          '25.2',
          'Harassment, hate speech, spamming other Users, posting misleading '
              'Registries, or exploiting the SOS/urgent-gifting feature '
              '(where launched) for non-genuine purposes are treated as '
              'violations of these Community Guidelines and Clause 9.',
        ),
        LegalClause(
          '25.3',
          'Wishtick may issue warnings, restrict features, or take '
              'enforcement action under Clauses 26–27 for repeated or serious '
              'violations.',
        ),
      ]),

      LegalSection(26, 'User Suspension', [
        LegalClause(
          '26.1',
          'Wishtick may temporarily suspend an Account, in whole or in part, '
              'where it reasonably believes a User has violated these Terms, '
              'applicable law, or poses a risk to the Platform, other Users, '
              'or Affiliate Partners.',
        ),
        LegalClause(
          '26.2',
          'Wishtick will make reasonable efforts to notify the affected User '
              'of the reason for suspension, except where notice would be '
              'unlawful, would compromise an investigation, or is otherwise '
              'inappropriate in the circumstances.',
        ),
        LegalClause(
          '26.3',
          'A suspended User may seek review by contacting the Grievance '
              'Officer.',
        ),
      ]),

      LegalSection(27, 'Account Termination', [
        LegalClause(
          '27.1',
          'You may terminate your Account at any time through in-app settings '
              'or by writing to ${LegalEntity.supportEmail}, subject to '
              'completion of any pending obligations.',
        ),
        LegalClause(
          '27.2',
          'Wishtick may terminate, permanently disable, or suspend an Account '
              'for material or repeated breach of these Terms, unlawful '
              'activity, extended inactivity, or as required by law, with '
              'notice where reasonably practicable.',
        ),
        LegalClause(
          '27.3',
          'Upon termination, your right to access the Platform ceases '
              'immediately; Clauses 19–23 (IP/Content), 30–33 '
              '(Liability/Indemnity), and 34–37 (Dispute Resolution) survive '
              'termination.',
        ),
        LegalClause(
          '27.4',
          'Data retention and deletion following termination is governed by '
              'Clause 28 and the Privacy Policy.',
        ),
      ]),

      LegalSection(28, 'Data Retention', [
        LegalClause(
          '28.1',
          'Wishtick retains personal data and Account information for as long '
              'as reasonably necessary to provide the Platform’s services, '
              'comply with legal obligations, resolve disputes, and enforce '
              'these Terms, as further detailed in Privacy Policy Clause 28.',
        ),
        LegalClause(
          '28.2',
          'Upon Account deletion, Wishtick will delete or anonymize personal '
              'data within the timelines set out in the Privacy Policy, '
              'except where retention is required by law (e.g., under tax, '
              'accounting, or judicial process requirements).',
        ),
      ]),

      LegalSection(29, 'Privacy Commitment', [
        LegalClause(
          '29.1',
          'Wishtick’s collection, use, storage, and disclosure of personal '
              'data is governed by the Privacy Policy, which forms an '
              'integral part of these Terms.',
        ),
        LegalClause(
          '29.2',
          'Wishtick processes personal data in accordance with the Digital '
              'Personal Data Protection Act, 2023, and applicable rules, on '
              'the basis of consent or other permitted legal grounds as '
              'described in the Privacy Policy.',
        ),
      ]),

      LegalSection(30, 'Limitation of Liability', [
        LegalClause(
          '30.1',
          'To the maximum extent permitted by applicable law, Wishtick, its '
              'directors, officers, employees, and affiliates shall not be '
              'liable for any indirect, incidental, consequential, special, '
              'exemplary, or punitive damages, including loss of profits, '
              'data, goodwill, or opportunity, arising out of or related to '
              'your use of the Platform.',
        ),
        LegalClause(
          '30.2',
          'Wishtick’s aggregate liability for any claim arising under these '
              'Terms, to the extent liability cannot be excluded under '
              'applicable law, shall not exceed the higher of (a) Rs. 2,000 '
              '(Indian Rupees Two Thousand), or (b) the amount, if any, paid '
              'by you to Wishtick directly for the specific service giving '
              'rise to the claim in the twelve (12) months preceding the '
              'claim.',
        ),
        LegalClause(
          '30.3',
          'Wishtick is not liable for:',
          items: [
            'acts or omissions of Affiliate Partners or third-party '
                'retailers;',
            'delivery delays, damaged, or non-conforming Products;',
            'payment gateway failures once such features are introduced;',
            'inaccuracies in AI Recommendations; or',
            'UGC posted by other Users.',
          ],
        ),
        LegalClause(
          '30.4',
          'Nothing in this Clause excludes liability that cannot be excluded '
              'under applicable Indian law, including under the Consumer '
              'Protection Act, 2019, in respect of Wishtick’s own direct '
              'acts.',
        ),
      ]),

      LegalSection(31, 'Disclaimer of Warranties', [
        LegalClause(
          '31.1',
          'The Platform is provided on an “as is” and “as available” basis, '
              'without warranties of any kind, whether express, implied, or '
              'statutory, including implied warranties of merchantability, '
              'fitness for a particular purpose, non-infringement, or '
              'uninterrupted/error-free operation, to the extent permitted by '
              'applicable law.',
        ),
        LegalClause(
          '31.2',
          'Wishtick does not warrant that AI Recommendations, Affiliate '
              'Partner listings, or third-party Product information will be '
              'accurate, complete, or current at all times.',
        ),
      ]),

      LegalSection(32, 'Force Majeure', [
        LegalClause(
          '32.1',
          'Wishtick shall not be liable for any failure or delay in '
              'performance resulting from causes beyond its reasonable '
              'control, including acts of God, natural disasters, war, '
              'terrorism, riots, pandemic, governmental action, internet or '
              'telecommunications failures, power outages, or failures of '
              'third-party service providers (including cloud infrastructure, '
              'payment gateways, or Affiliate Partners).',
        ),
        LegalClause(
          '32.2',
          'Performance obligations affected by a Force Majeure event are '
              'suspended for the duration of such event, and Wishtick will '
              'make reasonable efforts to resume normal operations promptly '
              'thereafter.',
        ),
      ]),

      LegalSection(33, 'Indemnification', [
        LegalClause(
          '33.1',
          'You agree to indemnify, defend, and hold harmless Wishtick, its '
              'directors, officers, employees, and affiliates from and '
              'against any claims, liabilities, damages, losses, and expenses '
              '(including reasonable legal fees) arising out of or connected '
              'with:',
          items: [
            'your breach of these Terms;',
            'your UGC;',
            'your violation of any law or third-party right, including '
                'intellectual property or privacy rights;',
            'your misuse of the Platform, including fraudulent '
                'Registry/Wishlist activity; or',
            'disputes between you and any Affiliate Partner or other User.',
          ],
        ),
        LegalClause(
          '33.2',
          'Wishtick reserves the right to assume exclusive control and '
              'defence of any matter subject to indemnification by you, in '
              'which case you agree to cooperate with Wishtick’s defence.',
        ),
      ]),

      LegalSection(34, 'Dispute Resolution', [
        LegalClause(
          '34.1',
          'In the event of any dispute, controversy, or claim arising out of '
              'or relating to these Terms (“Dispute”), the parties shall '
              'first attempt to resolve it amicably through good-faith '
              'negotiation within thirty (30) days of written notice of the '
              'Dispute.',
        ),
        LegalClause(
          '34.2',
          'If the Dispute is not resolved amicably within such period, it '
              'shall be referred to arbitration under Clause 35.',
        ),
      ]),

      LegalSection(35, 'Arbitration', [
        LegalCallout(
          'Arbitration does not take away your right to go to a Consumer '
          'Forum. Clause 35.5 says so expressly.',
          tone: LegalTone.good,
        ),
        LegalClause(
          '35.1',
          'Any Dispute not resolved under Clause 34 shall be referred to and '
              'finally resolved by arbitration under the Arbitration and '
              'Conciliation Act, 1996, as amended from time to time.',
        ),
        LegalClause(
          '35.2',
          'The arbitration shall be conducted by a sole arbitrator appointed '
              'by Wishtick, and the seat and venue of arbitration shall be '
              'Mumbai, Maharashtra, India.',
        ),
        LegalClause(
          '35.3',
          'The language of arbitration shall be English, and the arbitral '
              'award shall be final and binding on the parties, subject to '
              'applicable law.',
        ),
        LegalClause(
          '35.4',
          'Nothing in this Clause prevents either party from seeking urgent '
              'interim relief from a competent court.',
        ),
        LegalClause(
          '35.5',
          'Nothing in this Clause is intended to override a consumer’s '
              'statutory right to approach a Consumer Forum/Commission under '
              'the Consumer Protection Act, 2019, where such right cannot be '
              'validly excluded by contract.',
        ),
      ]),

      LegalSection(36, 'Governing Law', [
        LegalClause(
          '36.1',
          'These Terms are governed by and construed in accordance with the '
              'laws of India, without regard to conflict-of-law principles.',
        ),
      ]),

      LegalSection(37, 'Jurisdiction', [
        LegalClause(
          '37.1',
          'Subject to Clause 35 (Arbitration), the courts at Mumbai, '
              'Maharashtra, India shall have exclusive jurisdiction over any '
              'matters not required to be arbitrated or where interim relief '
              'is sought.',
        ),
      ]),

      LegalSection(38, 'Grievance Officer', [
        LegalClause(
          '38.1',
          'In accordance with the Information Technology Act, 2000, the '
              'Intermediary Guidelines Rules, 2021, and the Consumer '
              'Protection (E-Commerce) Rules, 2020 (as applicable), Wishtick '
              'has appointed a Grievance Officer:',
        ),
        LegalContact(
          role: 'Grievance Officer',
          name: LegalEntity.grievanceOfficerName,
          designation: LegalEntity.grievanceOfficerTitle,
          email: LegalEntity.supportEmail,
          phone: LegalEntity.grievanceOfficerPhone,
        ),
        LegalClause(
          '38.2',
          'The Grievance Officer will acknowledge complaints within 24 hours '
              'and endeavour to resolve them within the statutory timeline '
              '(currently 15 days for general complaints, and 72 hours for '
              'specified categories under the Intermediary Guidelines Rules, '
              '2021).',
        ),
      ]),

      LegalSection(39, 'Contact Information', [
        LegalParagraph('For questions regarding these Terms, contact:'),
        LegalContact(
          role: LegalEntity.name,
          name: LegalEntity.brand,
          email: LegalEntity.supportEmail,
        ),
      ]),

      LegalSection(40, 'Modification of Terms', [
        LegalClause(
          '40.1',
          'Wishtick may amend these Terms from time to time to reflect '
              'changes in law, features (including future payment, wallet, or '
              'marketplace functionality), or business practices.',
        ),
        LegalClause(
          '40.2',
          'Material changes will be notified via the Platform, registered '
              'email, or push notification at least '
              '${LegalEntity.termsChangeNoticeDays} days prior to the '
              'effective date, except where immediate change is required by '
              'law.',
        ),
        LegalClause(
          '40.3',
          'Continued use of the Platform after the effective date of updated '
              'Terms constitutes acceptance of the revised Terms.',
        ),
      ]),
    ],
  );
}
